# Uczenie maszynowe - Ćwiczenie 1 - NumPy - Zadania

**Zadanie 1**. Sprawdź do czego służą i przetestuj działanie następujących funkcji tworzących tablice `ndarray`:
1. `asarray`
2. `ones_like`
3. `zeros_like`
4. `full`
5. `full_like`
6. `eye`
7. `identity`

In [1]:
import numpy as np

**Zadanie 2**. Sprawdź, w jaki sposób są konwertowane przez funkcję `astype` niecałkowite wartości zmiennoprzecinkowe na wartości całkowite.

Szczegółowa informacja o typach wykorzystywanych w NumPy: https://numpy.org/doc/stable/reference/arrays.scalars.html#

**Zadanie 3**. Przekonwertuj tablicę wartości zmiennoprzecinkowych na tablicę stringów. Następnie przekonwertuj tablicę stringów z powrotem na wartości zmiennoprzecinkowe.

**Zadanie 4**. Zaprezentuj przykład rozgłaszania na dowolnej dwuargumentowej operacji gdzie pierwszym argumentem jest tablica trójwymiarowa, a drugim argumentem tablica dwuwymiarowa.

**Zadanie 5**. Przeczytaj w dokumentacji zastosowanie następujących metod a następnie przetestuj ich działanie na dowolnej tablicy dwuwymiarowej:
1. `sum`
2. `mean`
3. `std`
4. `var`
5. `min` 
6. `max`
7. `argmin`
8. `argmax`
9. `cumsum`
10. `cumprod`

**Zadanie 8.** Wygeneruj wektor stworzony z wektora [1, 2, 3], aby każdy element powtarzał się 4 razy i taka sekwencja była powtórzona 3-krotnie.

**Zadanie 9.** Wygeneruj wektor wartości od 1 do 10 co 0.25.

**Zadanie 10.** Wygeneruj wektor 43 wartości równomiernie  od 1 do 10.

**Zadanie 11.** Wyświetl co trzeci element z powyższego wektora.

**Zadanie 12.** Wyjaśnij wynik działania komendy `np.arange(6) – 1`

**Zadanie 13.** Utwórz macierz o 3 wierszach i 2 kolumnach poprzez:  
1. wypełnienie jej wierszowo wektorem (1,2,3,4,5,6),  
1. wypełnienie jej kolumnowo wektorem (1,2,3,4,5,6),  
1. złożenie wektorów (1,2,3) i (4,5,6),  
1. złożenie wektorów (1,4), (2,5) i (3,6).  

**Zadanie 14.** Utwórz macierz A o 6 wierszach i 6 kolumnach wypełnioną wierszowo liczbami od 1 do 36. Następnie korzystając z indeksowania utwórz macierz B:
1. o 3 wierszach i 3 kolumnach zawierającą elementy z wierszy o parzystych numerach i kolumn o nieparzystych numerach z macierzy A, przy czym kolumny w odwrotnej kolejności, czyli: pierwszy wiersz macierzy B będzie zawierał liczby 11, 9, 7, drugi 23, 21, 19, a trzeci 35, 33 i 31,
1. składającą się z dwóch ostatnich wierszy macierzy A,
1. składającą się z dwóch środkowych kolumn macierzy A,

**Zadanie 15**. Posortuj poniższą tablicę w wierszach.

In [101]:
T = np.array([[5,2,1,6],[4,8,3,1],[2,4,7,8]])

**Zadanie 16**. Posortuj powyższą tablicę w kolumnach.

**Zadanie 17**. Za pomocą `np.argsort()` podaj numery elementów oryginalnej tablicy w każdym wierszu, gdyby była ona posortowana w wierszach.

**Zadanie 18**. Poniższą tablicę posortuj zgodnie z porządkiem leksykograficznym na podstawie kolumny drugiej, w następnej kolejności na podstawie kolumny czwartej, a ostatecznie szóstej.

In [102]:
T = np.array([[5,2,5,2,7,4],[2,2,1,5,4,3],[1,3,4,1,4,5],[1,3,1,1,2,2]])

**Zadanie 19**. Za pomocą `np.hsplit()` podziel powyższą tablicę na 3 równe części.

In [103]:
T

array([[5, 2, 5, 2, 7, 4],
       [2, 2, 1, 5, 4, 3],
       [1, 3, 4, 1, 4, 5],
       [1, 3, 1, 1, 2, 2]])

**Zadanie 20**. Za pomocą `np.hsplit()` podziel powyższą tablicę na 4 części tak, aby w pierwszej , trzeciej i czwartej części znalazła się tylko jedna kolumna, a w drugiej części 3 kolumny.

**Zadanie 21**. Za pomocą `np.vsplit()` podziel powyższą tablicę na 3 dowolne części.

**Zadanie 22**. W trzech powyższych zadaniach, po podziale scal z powrotem części w jedną tablicę za pomocą `np.vstack()` lub `np.hstack()`.

**Zadanie 23**. Co robi z wektorem *w* poniższa operacja?

In [104]:
w = np.arange(1,11)
w = w[:, np.newaxis]

**Zadanie 24**. Co stanie się, jeżeli w powyszej opercji zamienimy pozycje indeksowania?

**Zadanie 25**. Korzystając z powyższego wektora i operatora `*`, wykorzystaj rozgłaszanie do wyliczenia tabliczki mnożenia do 100.

**Zadanie 26**. Wykorzystaj funkcję `np.nonzero()` aby uzyskać indeksy wierszy i kolumn wszystkich elementów z tablicy z zadania 10, która są jednocześnie nie mniejsze od 2 i mniejsze od 7. Wypisz wszystkie takie pary (nr_wiersza, nr_kolumny) na ekranie (podpowiedź: komenda `zip`).

In [105]:
np.nonzero((T >= 2) & (T < 7))

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 5, 0, 1, 3, 4, 5, 1, 2, 4, 5, 1, 4, 5], dtype=int64))

**Zadanie 27**. Korzystając z `np.unique()`, w poniższym wektorze znajdź wszystkie elementy unikatowe, ich indeksy oraz liczbę powtórzeń każdego z nich.

In [106]:
w = np.array([1,2,2,2,3,1,3,1,4,4,5,6,5,7,8,8])

**Zadanie 28**. Korzystając z `np.unique()`, w poniższej tablicy znajdź wszystkie unikatowe wiersze, ich indeksy oraz liczbę powtórzeń każdego z nich.

In [107]:
T = np.array([[1,2],[2,1],[2,2],[2,2],[2,3],[3,2],[1,2],[1,4],[2,1]])

**Zadanie 29** (*). Podczas ostatniego wykładu podano cztery sposoby liczenia odległości między klastrami. Wczytaj klastry z plików `klaster A.csv`, `klaster B.csv` i `klaster C.csv` za pomocą `np.loadtxt()`. Następnie wylicz odległości między każdą parą klastrów na każdy z czterech sposobów korzystając z możliwości NumPy. 

**Zadanie 30** (*). Dla każdego sposobu pomiaru odległości pomiędzy klastrami wylicz miarę $wc(C)/bc(C)$.