dr inż. Mateusz Gorczyca

### Uczenie maszynowe: 

# NumPy
\
\
\
semestr zimowy 2023/24

Na podstawie:  
- rozdz. 4 książki `Wes McKinney, "Python w analizie danych. Przetwarzanie danych za pomocą pakietów Pandas i NumPy oraz środowiska IPython. Wydanie III", Helion, 2023`, https://helion.pl/ksiazki/python-w-analizie-danych-przetwarzanie-danych-za-pomoca-pakietow-pandas-i-numpy-oraz-srodowiska-jup-wes-mckinney,pyanda.htm#format/d

 - dokumentacji NumPy: 
    - https://numpy.org/doc/stable/
    - https://numpy.org/doc/stable/user/absolute_beginners.html
    - https://numpy.org/doc/stable/user/index.html
 - Markdown:  
     https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet

### Plan wykładu:
 - Jupyter notebook
 - Jupyter markdown
 - Rise
 - Wstęp do NumPy
 - `ndarray` - $n$-wymiarowy obiekt tablicowy
 - Tworzenie obiektu `ndarray`

 - Typ danych `ndarray`: `dtype`
 - Wektoryzacja
 - Indeksowanie
 - Indeksowanie wektorami
 - Transpozycja, permutacja osi
 - Funkcje uniwersalne
 - Metody warunkowe
 - Metody matematyczne i statystyczne tablic

 - Metody dla tablic wartości logicznych
 - Sortowanie
 - Operacje na zbiorach
 - Przykład zastosowania

# Wstęp

NumPy jest pakietem do obliczeń numerycznych Python. Jest znacznie bardziej efektywny w przetwarzaniu danych tablicowych, niż standardowe typy danych Python.

In [1]:
import numpy as np

In [3]:
numpy_array = np.arange(100000000)
%time numpy_array = numpy_array * 2

CPU times: total: 125 ms
Wall time: 138 ms


In [4]:
python_list = list(range(100000000))
%time python_list = [x * 2 for x in python_list]

CPU times: total: 7.77 s
Wall time: 7.79 s


# `ndarray` - $n$-wymiarowy obiekt tablicowy

Tworzenie tablicy na podstawie listy

In [5]:
tablica = np.array([1,2,3,4,5,6])
tablica

array([1, 2, 3, 4, 5, 6])

In [6]:
tablica = np.array([[1,2],[3,4],[5,6]])
tablica

array([[1, 2],
       [3, 4],
       [5, 6]])

Tworzenie losowej tablicy dwuwymiarowej o 3 wierszach i 4 kolumnach

In [7]:
tablica = np.random.randn(3,4)
tablica

array([[ 0.34008359,  2.21324041, -1.33776105, -1.21450123],
       [ 2.03405648,  0.95443669, -1.14577485,  1.55954815],
       [ 0.10173367,  1.39150312,  0.5493102 , -1.7295383 ]])

Dla obiektów `ndarray` możemy wykorzystywać operatory arytmetyczne

In [8]:
print(tablica)
tablica*20

[[ 0.34008359  2.21324041 -1.33776105 -1.21450123]
 [ 2.03405648  0.95443669 -1.14577485  1.55954815]
 [ 0.10173367  1.39150312  0.5493102  -1.7295383 ]]


array([[  6.80167182,  44.26480818, -26.75522104, -24.29002457],
       [ 40.68112956,  19.08873382, -22.91549695,  31.190963  ],
       [  2.03467331,  27.83006242,  10.98620399, -34.59076594]])

In [9]:
print(tablica)
tablica - 3*tablica

[[ 0.34008359  2.21324041 -1.33776105 -1.21450123]
 [ 2.03405648  0.95443669 -1.14577485  1.55954815]
 [ 0.10173367  1.39150312  0.5493102  -1.7295383 ]]


array([[-0.68016718, -4.42648082,  2.6755221 ,  2.42900246],
       [-4.06811296, -1.90887338,  2.29154969, -3.1190963 ],
       [-0.20346733, -2.78300624, -1.0986204 ,  3.45907659]])

Atrybuty obiektu `ndarray` zawierają, m.in., liczbę wymiarów, kształt i typ danych

In [10]:
print(tablica)
tablica.ndim # tablica dwuwymiarowa

[[ 0.34008359  2.21324041 -1.33776105 -1.21450123]
 [ 2.03405648  0.95443669 -1.14577485  1.55954815]
 [ 0.10173367  1.39150312  0.5493102  -1.7295383 ]]


2

In [11]:
tablica.shape # dla tablicy 2-wymiarowej będzie to liczba wierszy i kolumn

(3, 4)

In [12]:
tablica.dtype # tutaj będzie to typ zmiennoprzecinkowy (zapisany na 64 bitach)

dtype('float64')

## Tworzenie obiektu `ndarray`

Tworzenie tablicy na podstawie obiektu sekwencyjnego.

In [13]:
dane = list(range(10))
print(dane)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
tablica = np.array(dane)
tablica # tablica jednowymiarowa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
dane2 = [dane, list(range(10,20))]
tablica2 = np.array(dane2)
tablica2 # tablica dwuwymiarowa

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Podczas tworzenia tablicy na podstawie danych wejściowych NumPy samodzielnie próbuje ustalić typ danych

In [16]:
print(tablica2)
tablica2.dtype

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


dtype('int32')

Można jednak jawnie określić typ danych.

In [17]:
dane3 = [1.0, 2.0, 3.0]
tablica3 = np.array(dane2)
tablica3.dtype

dtype('int32')

Tworzenie tablic wypełnionych zerami `np.zeros()`, jedynkami `np.ones()` i wartościami nieokreślonymi `np.empty()`

In [18]:
np.zeros((4,2)) # pierwszy argument to krotka z rozmiarami wymiarów

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [20]:
np.empty(5) # tylko jeden wymiar; komórki pamięci nie są inicjowane

array([0.00000000e+000, 8.29053751e-312, 8.29053752e-312, 8.29053750e-312,
       1.89120735e+219])

Tworzenie tablicy za pomocą funkcji `np.arange()`, odpowiednika `range()`

In [21]:
np.arange(5,125,10) # początek, koniec, krok

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115])

## Typ danych `ndarray`: `dtype`

Przy tworzeniu tablicy można jawnie podać typ danych przechowywanych w tablicy

In [22]:
tablica_int = np.arange(10, dtype=np.int32)
tablica_int

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
tablica_int.dtype

dtype('int32')

In [24]:
tablica_double = np.arange(10, dtype=np.double)
tablica_double

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
tablica_double.dtype

dtype('float64')

Konwersja typu za pomocą `astype`

In [26]:
tablica_int2 = tablica_double.astype(np.int32)
tablica_int2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Szczegółowa informacja o typach wykorzystywanych w NumPy: https://numpy.org/doc/stable/reference/arrays.scalars.html#

## Wektoryzacja

Podobnie jak w języku R, pewne operacja działające na wszystkich elementach tablicy nie wymagają wykorzystywania pętli `for`. Poniżej przykład analogiczne do omawianych w trakcie poprzedniego semestru w języku R (RWprowadzenie2022 - część 1.pdf)

In [27]:
wektorA = np.arange(1,7)
wektorB = np.arange(-4,2,1)
wektorA

array([1, 2, 3, 4, 5, 6])

In [29]:
wektorB

array([-4, -3, -2, -1,  0,  1])

In [30]:
wektorA + wektorB

array([-3, -1,  1,  3,  5,  7])

In [31]:
print(wektorA)
print(wektorB)

[1 2 3 4 5 6]
[-4 -3 -2 -1  0  1]


In [32]:
wektorA - wektorB

array([5, 5, 5, 5, 5, 5])

In [33]:
display(wektorA)
wektorD = np.arange(-1,-5,-1)
wektorD

array([1, 2, 3, 4, 5, 6])

array([-1, -2, -3, -4])

In [34]:
wektorA + wektorD # jaki był rezultat w R?

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [35]:
print(wektorA)
wektorE = np.array(-1)
print(wektorE)
wektorA * wektorE

[1 2 3 4 5 6]
-1


array([-1, -2, -3, -4, -5, -6])

Porównania:

In [37]:
wektorA

array([1, 2, 3, 4, 5, 6])

In [36]:
wektorA < 4

array([ True,  True,  True, False, False, False])

In [38]:
print(wektorA)
wektorF = np.arange(4,-2,-1)
print(wektorF)
wektorA <= wektorF

[1 2 3 4 5 6]
[ 4  3  2  1  0 -1]


array([ True,  True, False, False, False, False])

Dla operacji na tablicach o nierównych rozmiarach stosuje się tzw. rozłgaszanie (broadcasting): https://numpy.org/doc/stable/user/basics.broadcasting.html

## Indeksowanie

Dla tablic jednowymiarowych indeksowanie wygląda tak, jak w standardowych typach sekwencyjnych:

In [39]:
tablica = np.arange(100,110)
print(tablica)
tablica[2:6]

[100 101 102 103 104 105 106 107 108 109]


array([102, 103, 104, 105])

Przy przypisaniu do zakresu stosowane jest rozgłaszanie

In [40]:
print(tablica)
tablica[2:6] = -1
tablica

[100 101 102 103 104 105 106 107 108 109]


array([100, 101,  -1,  -1,  -1,  -1, 106, 107, 108, 109])

Uwaga! Przypisanie wycinka tablicy nie tworzy kopii tego wycinka, lecz nadal odnosi się do tej tablicy!

In [41]:
print(tablica)
wycinek = tablica[2:6]
print(wycinek)
wycinek[:] = -100
print(wycinek)
print(tablica)

[100 101  -1  -1  -1  -1 106 107 108 109]
[-1 -1 -1 -1]
[-100 -100 -100 -100]
[ 100  101 -100 -100 -100 -100  106  107  108  109]


Aby operować na kopii, należy ją jawnie utworzyć:

In [42]:
print(tablica)
wycinek = tablica[2:6].copy()
print(wycinek)
wycinek[:] = 1000 # teraz modyfikujemy tylko kopię w wycinku
print(wycinek)
print(tablica)

[ 100  101 -100 -100 -100 -100  106  107  108  109]
[-100 -100 -100 -100]
[1000 1000 1000 1000]
[ 100  101 -100 -100 -100 -100  106  107  108  109]


Dla tablic o większej liczbie wymiarów indeksowanie jest rekurencyjne

Tworzenie tablicy trójwymiarowej na podstawie następującego wektora:

In [43]:
print(np.arange(60))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [44]:
tablica = np.arange(60).reshape((3,4,5)) # zmiana kształtu z wektora na tablicę trójwymiarową
tablica 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [45]:
tablica[1] # rezultat to dwuwymiarowa tablica

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [46]:
tablica[1][2] # rezultat to jednowymiarowa tablica

array([30, 31, 32, 33, 34])

In [47]:
tablica[1][2][3] # rezultat to skalar

33

Alternatywny sposób adresowania z przecinkami

In [48]:
tablica[1,2] # rezultat to jednowymiarowa tablica

array([30, 31, 32, 33, 34])

In [49]:
tablica[1,2,3] # rezultat to skalar

33

Przykład rozgłaszania przy indeksowaniu

In [50]:
tablica

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [51]:
tablica[1] = 7
tablica

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

Podawanie zakresu wycinka dla każdego wymiaru

In [ ]:
tablica

In [52]:
tablica[:1,2:4,1:]

array([[[11, 12, 13, 14],
        [16, 17, 18, 19]]])

Możliwe jest także indeksowanie za pomocą warunków logicznych

In [53]:
tablica

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [54]:
parzystosc = np.array(['parzysta', 'nieparzysta', 'parzysta'])
print(parzystosc=='parzysta')
tablica[parzystosc=='parzysta',2:4,:]

[ True False  True]


array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

Użycie znaku `~` powoduje wstawienie wszystkich indeksów oprócz podanych

In [55]:
tablica

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7],
        [ 7,  7,  7,  7,  7]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [58]:
tablica[~(parzystosc=='parzysta'),~2:4,:] # które numery wierszy są wyświetlane?

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

Możliwe jest tworzenie bardziej skomplikowanych warunków logicznych z wykorzystaniem operatorów `|` (lub), `&` (i) oraz `!` (negacja).

## Indeksowanie wektorami

Możliwe jest także indeksowanie wektorami liczba całkowitych:

In [60]:
tablica = np.arange(10,20)
print(tablica)
tablica_indeksow = np.array([5,4,-1,9])
print(tablica_indeksow)

[10 11 12 13 14 15 16 17 18 19]
[ 5  4 -1  9]


In [61]:
print(tablica[tablica_indeksow])

[15 14 19 19]


W przypadku podania większej liczby argumentów jako indeksy, wybierane są krotki z poszczególnych pozycji argumentów:

In [62]:
tablica = np.arange(4*5*6).reshape((4,5,6))
tablica

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [ ]:
# pierwsza strona trzeci wiersz, trzecia strona czwarty wiersz, czwarta strona piąty wiersz

In [63]:
tablica[[0,2,3], [2,3,4]] 

array([[ 12,  13,  14,  15,  16,  17],
       [ 78,  79,  80,  81,  82,  83],
       [114, 115, 116, 117, 118, 119]])

In [64]:
tablica[[0,2,3], [2,3,4], [-5,-4,-3]]

array([ 13,  80, 117])

W przypadku indeksowania wektorami całkowitoliczbowymi tworzone są kopie (w przeciwieństwie do wycinków).

## Transpozycja, permutacja osi

Tablice dysponują atrybutem T dającym dostęp do tablicy transponowanej

In [65]:
tablica = np.arange(3*6).reshape((3,6))
tablica

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [66]:
tablica.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

Możliwe jest także wykorzystanie metody `transpose`

In [67]:
tablica.transpose()

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

W przypadku tablic o większej liczbie wymiarów do metody transpose możemy podać permutację, która określa w jaki sposób zostaną zamienione osie

In [68]:
tablica = np.arange(2*3*6).reshape((2,3,6))
tablica

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [69]:
tablica.transpose((2,0,1)) # czy ktoś to jeszcze rozumie? 

array([[[ 0,  6, 12],
        [18, 24, 30]],

       [[ 1,  7, 13],
        [19, 25, 31]],

       [[ 2,  8, 14],
        [20, 26, 32]],

       [[ 3,  9, 15],
        [21, 27, 33]],

       [[ 4, 10, 16],
        [22, 28, 34]],

       [[ 5, 11, 17],
        [23, 29, 35]]])

Do zamiany osi można wykorzystać metodę `swapaxes()`.

## Funkcje uniwersalne

NumPy oferuje zestaw funkcji uniwersalnych (*universal function*, w skróce *ufunc*) do operacji na tablicach.

In [3]:
tablica = np.arange(10).reshape(2,5)
tablica

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
np.sqrt(tablica) #pierwiastek z wszystkich elementów tablicy

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [5]:
tablica2 = np.arange(10,0,-1).reshape(2,5)
print(tablica2)
print(tablica)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
np.minimum(tablica, tablica2) # minimum z poszczególnych pozycji obu tablic

array([[0, 1, 2, 3, 4],
       [5, 4, 3, 2, 1]])

Pełny zestaw funcji uniwersalnych: https://numpy.org/doc/stable/reference/ufuncs.html

## Operacje warunkowe

Funkcja `where` umożliwia wykorzystanie tablic logicznych do wyboru elementów z tablic wejściowych

In [7]:
tabA = np.arange(1,11)
tabA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
tabB = np.arange(5,-5,-1)
tabB

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4])

In [9]:
tabLog = np.array([True, True, False, False, False, True, True, False, True, False])
tabLog

array([ True,  True, False, False, False,  True,  True, False,  True,
       False])

In [10]:
print(tabA)
print(tabB)
print(tabLog)

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  4  3  2  1  0 -1 -2 -3 -4]
[ True  True False False False  True  True False  True False]


In [11]:
np.where(tabLog, tabA, tabB)

array([ 1,  2,  3,  2,  1,  6,  7, -2,  9, -4])

In [12]:
np.where(tabA>=tabB, tabA, tabB)

array([ 5,  4,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.where(tabA>=tabB, tabLog, tabB) # skąd taki wynik?

array([5, 4, 0, 0, 0, 1, 1, 0, 1, 0])

Możliwe jest łączenie wartości skalarnych i tablic

In [15]:
print(tabA)
print(tabB)
print(tabLog)
print(tabA>=tabB)

[ 1  2  3  4  5  6  7  8  9 10]
[ 5  4  3  2  1  0 -1 -2 -3 -4]
[ True  True False False False  True  True False  True False]
[False False  True  True  True  True  True  True  True  True]


In [16]:
np.where(tabA>=tabB, 100, tabB)

array([  5,   4, 100, 100, 100, 100, 100, 100, 100, 100])

## Metody matematyczne i statystyczne tablic

Obiekty tablicowe NumPy posiadają podstawowe metody matematyczne i statystyczne, np. suma, średnia czy odchylenie standardowe

In [17]:
tablica = np.arange(10)
tablica

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tablica.mean()

4.5

In [19]:
tablica.sum()

45

In [20]:
tablica.std()

2.8722813232690143

Dla tablic wielowymiarowych możliwe jest podanie osi

In [21]:
tablica = np.arange(4*5).reshape((4,5))
tablica

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
tablica.sum(axis=0)

array([30, 34, 38, 42, 46])

In [23]:
tablica.sum(axis=1)

array([10, 35, 60, 85])

In [24]:
tablica.sum()

190

Pełna lista funkcji matematycznych: https://numpy.org/doc/stable/reference/routines.math.html
Pełna lista funkcji statystycznych: https://numpy.org/doc/stable/reference/routines.statistics.html

## Metody dla tablic wartości logicznych

Niektóre metody wykonane dla tablic logicznych konwertują `True` do wartości 1, a `False` do wartości 0

In [25]:
tab_log = np.array([True, True, False, False, False, True, True, False, True, False])
tab_log

array([ True,  True, False, False, False,  True,  True, False,  True,
       False])

In [26]:
tab_log.sum()

5

Metody `all` oraz `any` pozwalają stwierdzić, czy wszystkie bądź jakiekolwiek wartości tablicy zawierają `True`

In [27]:
print(tab_log)
tab_log.any()

[ True  True False False False  True  True False  True False]


True

In [28]:
tab_log.all()

False

In [29]:
tabA = np.arange(6)
tabA

array([0, 1, 2, 3, 4, 5])

In [30]:
tabB = np.arange(6,12)
tabB

array([ 6,  7,  8,  9, 10, 11])

In [31]:
tabA < tabB

array([ True,  True,  True,  True,  True,  True])

In [32]:
(tabA < tabB).any()

True

In [33]:
(tabA < tabB).all()

True

## Sortowanie

In [34]:
tablica = np.random.randn(20)
tablica

array([-1.30416192, -2.80962265, -2.10102215,  0.65837707, -0.50636097,
        0.23817525,  0.89557263, -1.62207509,  0.86266815, -0.60614475,
        1.47864372, -1.1077424 ,  0.36610181, -1.47263035,  0.31767583,
        0.56495589, -0.39756436, -0.7224295 , -0.72074317, -0.46982044])

In [35]:
tablica.sort()
tablica

array([-2.80962265, -2.10102215, -1.62207509, -1.47263035, -1.30416192,
       -1.1077424 , -0.7224295 , -0.72074317, -0.60614475, -0.50636097,
       -0.46982044, -0.39756436,  0.23817525,  0.31767583,  0.36610181,
        0.56495589,  0.65837707,  0.86266815,  0.89557263,  1.47864372])

## Operacje na zbiorach

Do tablic można stosować operacje dotyczące zbiorów

In [36]:
tablica = np.array([1,2,2,3,4,4,4,5])
tablica

array([1, 2, 2, 3, 4, 4, 4, 5])

Wartości unikatowe

In [37]:
np.unique(tablica)

array([1, 2, 3, 4, 5])

Które wartości z podanej tablicy zawiera tablica wejściowa?

In [38]:
wartosci = np.arange(-1,8)
print(wartosci)
print(tablica)

[-1  0  1  2  3  4  5  6  7]
[1 2 2 3 4 4 4 5]


In [39]:
np.in1d(wartosci,tablica)

array([False, False,  True,  True,  True,  True,  True, False, False])

Wszystkie operacje na zbiorach: https://numpy.org/doc/stable/reference/routines.set.html